### ISSUE TITLE
Search is not regexp anymore?

### ISSUE THREAD

**Issue by vanch3d** [maforget/Bedetheque-Scrapper-2#1]
Thanks for the fix for the `Could not create SSL/TLS secure channel` bug (cannot comment on reddit). 
It working fine again. However I noticed a significant change in terms of potency of the search for the scrapper. 

It used to be more flexible for partial titles and French accents. 

For example, a search for a string `Tout sera oublie`  would find the proper record `Tout sera oublié`
Similarly, a search for `Les oublies` would open a dialog for matching title like `Les oubliés` or `Les oubliés d'Annam`.

It looks like a RegExp problem for me. 
I didn't keep my old version before installing your fix so I cannot compare versions. 

Worth looking at ?

**Comment by vanch3d** [comment]
Just figured out that you had the 4.9 version tagged and packaged here. Will have a look as well.

**Comment by maforget** [comment]
The only thing I did was add 1 line that tells the Web Request to use the TLS1.2, because by default .Net 4.5 won't use it. The only other change I did was do a check if the base url exists on a check that adds it. So if there is a change somewhere it might be in the site. I personally never had a windows open up with choices, it either worked or didn't, I usually had to go to the site and search the name and rename the comic accordingly to have it worked.

I did some checkup and found out the reason that is totally unrelated. From what I saw, what is done is loading the first letter of the name like [C](https://www.bedetheque.com/bandes_dessinees_C.html), and find the name in that list. If it doesn't it tries to check in the Revue lists like [this](https://www.bedetheque.com/liste_revues_C.html), but this returns a 500 internal address on the site, so the code breaks and instead of continuing and doing a search, it just stops there. So the capability is there, just need to fix the code to ignore the revues lists. Like I said I never really saw this popup, so this must have been happening for a while.

If you want you can answer in French, if you want, I am just writing in English in case someone who doesn't speak French is just using the scrapper, don't know why the would.

I will release v4.11
