### ISSUE TITLE
Fail opening configuration and program

### ISSUE THREAD

**Issue by killo3967** [maforget/Bedetheque-Scrapper-2#18]
**Describe the bug**
In console and in messegabox appears this message "sequence item 0: expected bytes or byte array, str found"

**Expected behavior**
The problem

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://i.imgur.com/Hybjl6A.png)

Initialzing script 'RenumberBooks' from 'Autonumber.py'

Initialzing script 'CommitProposed' from 'CommitProposed.py'

Initialzing script 'NewComicBooks' from 'NewComics.py'

Initialzing script 'SaveCSVList' from 'OtherScripts.py'

Initialzing script 'RenameBookFiles' from 'OtherScripts.py'

Initialzing script 'SetComicInfoDirty' from 'OtherScripts.py'

Initialzing script 'ConfigureBookHasBeenOpened' from 'Sample.py'

Initialzing script 'GetBooksWith' from 'Sample.py'

Initialzing script 'AutoadjustTwoPageMode' from 'Sample.py'

Initialzing script 'DummySearch' from 'Sample.py'

Initialzing script 'DummyHtmlInfoPanel' from 'Sample.py'

Initialzing script 'WebLinkInfoPanel' from 'Sample.py'

Initialzing script 'DummyUIInfoPanel' from 'Sample.py'

Initialzing script 'ComicRackUserForum' from 'Sample.py'

Initialzing script 'FadeReadThumbnails' from 'Sample.py'

Initialzing script 'ShowStartupMessage' from 'Sample.py'

Initialzing script 'ShowShutdownMessage' from 'Sample.py'

Initialzing script 'ParseComicPath' from 'Sample.py'

Initialzing script 'BookHasBeenOpened' from 'Sample.py'

Initialzing script 'SearchAndReplace' from 'SearchAndReplace.py'

Initialzing script 'BD_start' from 'BedethequeScraper2.py'

Initialzing script 'ConfigureBD2Quick' from 'BedethequeScraper2.py'

Initialzing script 'ConfigureBD2' from 'BedethequeScraper2.py'

Initialzing script 'QuickScrapeBD2' from 'BedethequeScraper2.py'

Initialzing script 'cvs_config' from 'ComicVineScraper.py'

Initialzing script 'cvs_scrape' from 'ComicVineScraper.py'

Initialzing script 'backupManager_Startup' from 'BackupManager.py'

Initialzing script 'backupManager_Shutdown' from 'BackupManager.py'

Initialzing script 'backupManager' from 'BackupManager.py'

Initialzing script 'cr_summary_translate' from 'cr_summary_translate_v2.py'

Initialzing script 'Filter_comic_by_image_type' from 'Filter_comic_by_image_type.py'

Initialzing script 'OnStartup' from 'avif.py'

Initialzing script 'translate_summary_field' from 'Summary_Field_Translator.py'

Initialzing script 'cr_summary_translate' from 'Translate_Summary.py'
Calling 'OnStartup'...
Compilation of 'C:\Users\tomas\AppData\Roaming\cYo\ComicRack\Scripts\Modern Image Formats Support\avif.py'
- Modern Image Formats Support Loaded
Calling 'backupManager_Startup'...
Compilation of 'C:\Users\tomas\AppData\Roaming\cYo\ComicRack\Scripts\CR Backup Manager\BackupManager.py'
No se puede encontrar una parte de la ruta de acceso 'C:\Users\tomas\AppData\Local\cyo\ComicRack\cache\CustomThumbnail'.
Calling 'OnStartup'...
Calling 'OnStartup'...
Calling 'ConfigureBD2Quick'...
Compilation of 'C:\Users\tomas\AppData\Roaming\cYo\ComicRack\Scripts\Bedetheque Scraper 2\BedethequeScraper2.py'
sequence item 0: expected bytes or byte array, str found
````

Do you think i miss a Microsoft Visual C++ Redistributable Library ? I have the 2008,2010, 2012, 2013 and 2015-2022
I am doing a new pluging and when i load json library i have the same error. So, i think it's my system but i don't know what.

**Comment by maforget** [comment]
So there is no problem with my plugin? You just used it has a starting point for your own? When I said to check my plugin it was so you can see how the dependencies are included with the plugin instead of asking to copy files separately. This plugin isn't the best inspiration, I just maintain it. I would refer to the ComicVine Scrapper for example.

If so then there is nothing wrong with your computer, you should google the error you got. From what you are telling me and what I can gather you are trying to load a json string, but the command you are using is expecting a byte array. Either the library you are using doesn't work with a string, you need to use another command or you don't have the library installed. This isn't like installing the python interpreter and have a load of function available that you can just import and be done with (a couple seem to come with the ComicRack Script Interpreter). You actually need to copy the files in the folder (and their dependencies). Also this isn't Python 3.10, it's IronPython, which is old and based on Python 2.7, so if you are using AI to help you, the syntax and functions may be different, as are the library you may install.

Problem is IronPython isn't supported by nobody, so you don't have any IDE support for debugging and etc. Which is why any new plugin I've done is completely in .NET framework. The difference between python and C# is that C# is a statically typed language, which means that you need to know in advance what is the type and what are it's properties. So you can't just type book.FilePath, you need to have a book object and a FilePath property. So it's a little bit more difficult than python, but you catch almost all of these types of errors on compile instead of runtime.

Check https://github.com/maforget/ComicRack_FindImageResolution. The python is at the minimum to just load the .NET framework. Then I created a wrapper for the ComicRack functions (since it's a statically typed language) and I do everything in it. I can attach it to ComicRack and have breakpoints and debugging my plugin and check the value of all my variables and even the ones from ComicRack.

I would suggest to just get the Visual Studio Community 2022 and try it that way. You might have a problem in opening the solution, because I am targeting the same framework has ComicRack for ease (4.5). But only 4.5.1 is available by Microsoft (would probably work to just change it to 4.5.2, since it's auto installed on all windows machine or use [these instructions](https://www.gnostice.com/docs/docstudio_net/guide/_faq_buildinganddeployment_vs2022_and_netframework45.html) to install the pack for 4.5.

**Comment by killo3967** [comment]
First of all, I'm sorry it took me so long to reply, but I was doing a lot of tests.
The problem is not in your script. The problem is in the computer I was using for development which had Windows 10 Home installed and it seems that the operating system was not in very good condition.
After reinstalling everything now it works fine.

Thank you very much for your comments although I already knew it. I used the option of installing the Windows 8 SDK and the truth is that the VS2022 is working quite well. 

By the way, in your script I see that you didn't use the requests library, is there a reason why you use urllib and urllib2?

Regarding what you said about installing the local libraries, I think a better solution is to do an: 

mklink /D "c:\Program Files\ComicRack\Lib" "c:\Program Files\IronPython 2.7\Lib"

This allows you to access the libraries that are hanging from pip and are very interesting. It also allows you to install new libraries in Ironpython and have them accessible.
Once you know what you need, you can copy them locally for publishing. 

By the way, I don't know if it exists, but wouldn't it be nice to have a document about creating plugins ? I mean, how to set up your development environment, the documentation about hooks and comicrack libraries and what functions they have, what each one does, what parameters, etc. I'm sure there are a lot of people on this subreddit who have information on that, but it's very scattered.

**Comment by maforget** [comment]
I am not the original creator of this plugin, So I don't know why which libraries are used. Also I don't even know where they are used, if at all. All web request are done via the .NET framework libraries and not the python ones. Don't forget this is IronPython, which means Python and .NET Framework. A lot of plugin just use the .NET Framework libraries, since it's what ComicRack runs with, so they are all installed with the software.

The reason I suggested to check my other plugin is to not use IronPython at all. You will have a lot of obstacles going with an old unsupported framework. You can't even use the IronPython interpreter in Visual Studio 2022, it won't even load. Visual Studio doesn't support it either and it might be possible to make it work, it would require a lot of manually editing config files. I keep and an old version of Visual Studio to be able to debug this plugin and even then Visual Studio will hang while debugging because I believe they are too much variables.

As to the topic of dependencies. It's not as simple as copying 1 file here and there, you need to check it's own dependencies, and their dependencies, etc. If you only do it while publishing you risk the risk that some files would be missing and because you did a hardlink to the folder, you might not even be able to test it like a user that doesn't have these installed would. This is why you should include them directly with your project. Then you have always the same experience if it's just someone installing your plugin or cloning and trying to modify it. You can then also automate the building directly on Github via actions like I did.

All the information you talk about was on the ComicRack wiki, you can check it out via the Wayback Machine. Also decompiling the ComicRack code to check on all the functions and hooks is very easy.
